import io
import os
from datetime import datetime
from typing import List, Optional, Any


def _format_date(dt: Any) -> str:
    if dt is None:
        return "Unknown Date"
    if isinstance(dt, str):
        try:
            dt = datetime.fromisoformat(dt)
        except Exception:
            return dt
    return dt.strftime("%d %B %Y")


# ------------------------------------------------------------------
# TXT export
# ------------------------------------------------------------------

def export_txt(
    meeting_title: str,
    meeting_date: Any,
    participants: List[str],
    summary_text: str,
    decisions: List[str],
    action_items: List[dict],
    transcript_text: str,
) -> bytes:
    lines = [
        "=" * 72,
        f"MEETING MINUTES",
        f"Starlight Secondary School, Amuria District, Uganda",
        "=" * 72,
        f"Title      : {meeting_title}",
        f"Date       : {_format_date(meeting_date)}",
        f"Attendees  : {', '.join(participants) if participants else 'N/A'}",
        "",
        "EXECUTIVE SUMMARY",
        "-" * 40,
        summary_text or "No summary generated.",
        "",
        "KEY DECISIONS",
        "-" * 40,
    ]
    for i, d in enumerate(decisions, 1):
        lines.append(f"  {i}. {d}")
    if not decisions:
        lines.append("  No decisions extracted.")

    lines += [
        "",
        "ACTION ITEMS",
        "-" * 40,
    ]
    for i, a in enumerate(action_items, 1):
        assignee = a.get("assignee_name") or "Unassigned"
        deadline = a.get("deadline") or "No deadline"
        status = a.get("status", "pending").title()
        lines.append(f"  {i}. [{status}] {a.get('text', '')} — {assignee} (Due: {deadline})")
    if not action_items:
        lines.append("  No action items.")

    lines += [
        "",
        "FULL TRANSCRIPT",
        "-" * 40,
        transcript_text or "No transcript available.",
        "",
        "=" * 72,
        f"Generated by Online Meeting Summarizer on {datetime.now().strftime('%d %B %Y %H:%M')}",
        "=" * 72,
    ]
    return "\n".join(lines).encode("utf-8")


# ------------------------------------------------------------------
# PDF export
# ------------------------------------------------------------------

def export_pdf(
    meeting_title: str,
    meeting_date: Any,
    participants: List[str],
    summary_text: str,
    decisions: List[str],
    action_items: List[dict],
    transcript_text: str,
) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    BLUE = colors.HexColor("#1d4ed8")
    GRAY = colors.HexColor("#6b7280")
    DARK = colors.HexColor("#111827")

    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=20, leading=26, textColor=BLUE, spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, textColor=GRAY, spaceAfter=2
    )
    heading_style = ParagraphStyle(
        "Heading", parent=styles["Heading2"],
        fontSize=12, leading=16, textColor=BLUE, spaceBefore=14, spaceAfter=6
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=10, leading=15, textColor=DARK, spaceAfter=4
    )
    bullet_style = ParagraphStyle(
        "Bullet", parent=styles["Normal"],
        fontSize=10, leading=14, textColor=DARK, leftIndent=14, spaceAfter=3,
        bulletIndent=4, bulletFontSize=10
    )

    story = []

    # Header block
    story.append(Paragraph(meeting_title, title_style))
    story.append(Paragraph("Starlight Secondary School, Amuria District, Uganda", subtitle_style))
    story.append(Paragraph(f"Date: {_format_date(meeting_date)}", subtitle_style))
    if participants:
        story.append(Paragraph(f"Attendees: {', '.join(participants)}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=12))

    # Executive Summary
    story.append(Paragraph("Executive Summary", heading_style))
    story.append(Paragraph(summary_text or "No summary generated.", body_style))

    # Key Decisions
    story.append(Paragraph("Key Decisions", heading_style))
    if decisions:
        for d in decisions:
            story.append(Paragraph(f"• {d}", bullet_style))
    else:
        story.append(Paragraph("No decisions extracted.", body_style))

    # Action Items table
    story.append(Paragraph("Action Items", heading_style))
    if action_items:
        table_data = [["#", "Action", "Assignee", "Deadline", "Status"]]
        for i, a in enumerate(action_items, 1):
            table_data.append([
                str(i),
                Paragraph(a.get("text", "")[:80], body_style),
                a.get("assignee_name") or "Unassigned",
                str(a.get("deadline") or "—"),
                (a.get("status", "pending")).title(),
            ])
        tbl = Table(table_data, colWidths=[0.5 * cm, 8 * cm, 3 * cm, 3 * cm, 2 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(tbl)
    else:
        story.append(Paragraph("No action items.", body_style))

    # Full transcript (collapsed / smaller)
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    small_style = ParagraphStyle(
        "Small", parent=styles["Normal"],
        fontSize=8, leading=12, textColor=GRAY, spaceBefore=12
    )
    story.append(Paragraph("Full Transcript", heading_style))
    # Break transcript into paragraphs to avoid overflow
    for para in (transcript_text or "No transcript available.").split("\n"):
        if para.strip():
            story.append(Paragraph(para.strip(), small_style))

    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    story.append(Paragraph(
        f"Generated by Online Meeting Summarizer · {datetime.now().strftime('%d %B %Y %H:%M')}",
        subtitle_style
    ))

    doc.build(story)
    return buffer.getvalue()


# ------------------------------------------------------------------
# DOCX export
# ------------------------------------------------------------------

def export_docx(
    meeting_title: str,
    meeting_date: Any,
    participants: List[str],
    summary_text: str,
    decisions: List[str],
    action_items: List[dict],
    transcript_text: str,
) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Set page margins
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.2)
        section.right_margin = Inches(1.2)

    BLUE = RGBColor(0x1D, 0x4E, 0xD8)
    DARK = RGBColor(0x11, 0x18, 0x27)
    GRAY = RGBColor(0x6B, 0x72, 0x80)

    def add_heading(text: str, level: int = 1):
        h = doc.add_heading(text, level=level)
        for run in h.runs:
            run.font.color.rgb = BLUE

    def add_body(text: str):
        p = doc.add_paragraph(text)
        for run in p.runs:
            run.font.size = Pt(10)
            run.font.color.rgb = DARK

    # Title
    t = doc.add_heading(meeting_title, 0)
    for run in t.runs:
        run.font.color.rgb = BLUE
        run.font.size = Pt(20)

    doc.add_paragraph(f"Starlight Secondary School, Amuria District, Uganda").style = "Subtitle"
    doc.add_paragraph(f"Date: {_format_date(meeting_date)}")
    if participants:
        doc.add_paragraph(f"Attendees: {', '.join(participants)}")

    doc.add_paragraph()

    add_heading("Executive Summary", 1)
    add_body(summary_text or "No summary generated.")

    add_heading("Key Decisions", 1)
    if decisions:
        for d in decisions:
            p = doc.add_paragraph(d, style="List Bullet")
    else:
        add_body("No decisions extracted.")

    add_heading("Action Items", 1)
    if action_items:
        tbl = doc.add_table(rows=1, cols=5)
        tbl.style = "Table Grid"
        hdr = tbl.rows[0].cells
        for i, h in enumerate(["#", "Action", "Assignee", "Deadline", "Status"]):
            hdr[i].text = h
        for idx, a in enumerate(action_items, 1):
            row = tbl.add_row().cells
            row[0].text = str(idx)
            row[1].text = a.get("text", "")[:100]
            row[2].text = a.get("assignee_name") or "Unassigned"
            row[3].text = str(a.get("deadline") or "—")
            row[4].text = (a.get("status", "pending")).title()
    else:
        add_body("No action items.")

    add_heading("Full Transcript", 1)
    add_body(transcript_text or "No transcript available.")

    doc.add_paragraph()
    footer_p = doc.add_paragraph(
        f"Generated by Online Meeting Summarizer · {datetime.now().strftime('%d %B %Y %H:%M')}"
    )
    for run in footer_p.runs:
        run.font.color.rgb = GRAY
        run.font.size = Pt(8)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
